ShopApp.WebUI/Models/ResultMessage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ShopApp.WebUI.Models
{
    public class ResultMessage
    {
        public string Title { get; set; }
        public string Message { get; set; }
        public string Css { get; set; }
    }
}

ShopApp.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.Entities;
using ShopApp.WebUI.Models;

namespace ShopApp.WebUI.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        private IProductService _productService;
        private ICategoryService _categoryService;
        public AdminController(IProductService productService, ICategoryService categoryService)
        {

            _productService = productService;
            _categoryService = categoryService;
        }
        public IActionResult ProductList()
        {
            return View(new ProductListViewModel()
            {
                Products = _productService.GetAll()
            });
        }
        [HttpGet]
        public IActionResult CreateProduct()
        {
            return View(new ProductModel());
        }
        [HttpPost]
        public IActionResult CreateProduct(ProductModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = new Product()
                {
                    Name = model.Name,
                    Price = model.Price,
                    Description = model.Description,
                    ImageUrl = model.ImageUrl


                };
                if (_productService.Create(entity))
                {
                    return RedirectToAction("Index");
                }
                ViewBag.ErrorMessage = _productService.ErrorMessage;
                return View(model);

            }
            return View(model);

        }
        public IActionResult EditProduct(int? id)
        {
            if (id == null)
            {

                return NotFound();
            }
            var entity = _productService.GetByIdWithCategories((int)id);
            if (entity == null)
            {
                return NotFound();
            }
            var model = new ProductModel()
            {
                Id = entity.Id,
                Name = entity.Name,
                Description = entity.Description,
                ImageUrl = entity.ImageUrl,
                Price = entity.Price,
                SelectedCategories = entity.ProductCategories.Select(x => x.Category).ToList()

            };
            ViewBag.Categories = _categoryService.GetAll();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditProduct(ProductModel model, int[] categoryIds, IFormFile file)
        {
            if (ModelState.IsValid)
            {




                var entity = _productService.GetById(model.Id);
                if (entity == null)
                {
                    return NotFound();

                }
                entity.Name = model.Name;
                entity.ImageUrl = model.ImageUrl;
                entity.Description = model.Description;
                if (file!=null)
                {
                    entity.ImageUrl = file.FileName;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
                    using (var stream=new FileStream(path,FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }

                }
                
                _productService.Update(entity, categoryIds);
                return RedirectToAction("ProductList");
            }
            ViewBag.Categories = _categoryService.GetAll();
            return View(model);
        }
        [HttpPost]
        public IActionResult DeleteProduct(int productId)
        {
            var entity = _productService.GetById(productId);
            if (entity != null)
            {
                _productService.Delete(entity);

            }
            return RedirectToAction("Index");

        }

        public IActionResult CategoryList()
        {


            return View(new CategoryListViewModel()
            {
                Categories = _categoryService.GetAll()

            });
        }

        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategory(CategoryModel model)
        {
            var entity = new Category()
            {
                Name = model.Name
            };
            _categoryService.Create(entity);
            return RedirectToAction("CategoryList");
        }
        public IActionResult EditCategory(int id)
        {


            var entity = _categoryService.GetByIdWithProducts(id);


            return View(new CategoryModel()
            {
                Id = entity.Id,
                Name = entity.Name,
                Products = entity.ProductCategories.Select(x => x.Product).ToList()
            }); ;
        }
        [HttpPost]
        public IActionResult EditCategory(CategoryModel model)
        {
            var entity = _categoryService.GetById(model.Id);
            if (entity == null)
            {
                return NotFound();
            }
            entity.Name = model.Name;
            _categoryService.Update(entity);
            return RedirectToAction("CategoryList");
        }
        [HttpPost]
        public IActionResult DeleteCategory(int categoryId)
        {
            var entity = _categoryService.GetById(categoryId);
            if (entity != null)
            {
                _categoryService.Delete(entity);
            }
            return RedirectToAction("CategoryList");
        }
        [HttpPost]
        public IActionResult DeleteFromCategory(int categoryId, int productId)
        {
            _categoryService.DeleteFromCategory(categoryId, productId);
            return Redirect("/admin/editcategory/" + categoryId);

        }
    }
}

ShopApp.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.WebUI.Identity;
using ShopApp.WebUI.Models;

namespace ShopApp.WebUI.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private ICartService _cartService;
        private UserManager<ApplicationUser> _userManager;
        public CartController(ICartService cartService, UserManager<ApplicationUser> userManager)
        {

            _cartService = cartService;
            _userManager = userManager;
        }
        public  IActionResult Index()
        {
            var cart = _cartService.GetCartByUserId(_userManager.GetUserId(User));
            return View(new CartModel()
            {
                CartId = cart.Id,
                CartItems = cart.CartItems.Select(x => new CartItemModel()
                {
                    CartItemId = x.Id,
                    ProductId = x.ProductId,
                    Name = x.Product.Name,
                    Price = (decimal)x.Product.Price,
                    Quantity = x.Quantity,
                    ImageUrl = x.Product.ImageUrl,

                }).ToList()
            }) ; 
        }

        [HttpPost]
        public IActionResult AddToCart(int productId, int quantity)
        {
            _cartService.AddToCart(_userManager.GetUserId(User), productId, quantity);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult DeleteFromCart(int productId)
        {
            _cartService.DeleteFromCart(_userManager.GetUserId(User), productId );
            return RedirectToAction("Index");
        }
    }
}

ShopApp.WebUI/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ShopApp.Business.Abstract;
using ShopApp.Entities;
using ShopApp.WebUI.Models;

namespace ShopApp.WebUI.Controllers
{
    public class ShopController : Controller
    {
        private IProductService _productService;
        public ShopController(IProductService productService)
        {
            _productService = productService;

        }
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();

            }
            Product product = _productService.GetProducDetails((int)id);
            if (product == null)
            {
                return NotFound();

            }
            return View(new ProductDetailsModel()
            {
                Product = product,
                Categories = product.ProductCategories.Select(x => x.Category).ToList()
            });
        }
        //product/bilgisayar?page=3
        public IActionResult List(string category,int page=1)
        {
            const int pageSize = 3;
            //buradaki değeri kontol et string olarak veri gelmiyor
            return View(new ProductListViewModel()

            {
                PageInfo = new PageInfo()
                {
                    TotalItems = _productService.GetCountByCategory(category),
                    CurrentPage=page,
                    ItemsPerPage=pageSize,
                    CurrentCategory=category
                },
                Products = _productService.GetProductsByCategory(category, page, pageSize)

            }) ;
        }
    }
}

ShopApp.WebUI/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    @*<link href="~/modules/bootstrap/dist/css/style.css" rel="stylesheet" />*@
    <title>ShopApp</title>
</head>

<partial name="_navbar" />
<body>
    <div class="container ">
       
        <br />
        <br />
        <br />
        @if (TempData["message"]!=null)
        {
            <partial name="_resultmessage" model="@(TempData.Get<ResultMessage>("message"))"/>
        }
        

        @RenderBody()

    </div>

    <script src="~/modules/jquery/dist/jquery.min.js"></script>
    <script src="~/modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/27ecb554f9.js" crossorigin="anonymous"></script>

    @RenderSection("Script",false)
</body>
</html>

ShopApp.WebUI/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <a class="navbar-brand" href="#">ShopAPP</a>
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a href="#" class="nav-link active">Home</a>
                </li>
                <li class="nav-item">
                    <a asp-controller="Shop" asp-action="List" class="nav-link ">Products</a>
                </li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a asp-controller="Cart" asp-action="Index" class="nav-link ">Cart</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link ">Orders</a>
                    </li>
                    if (User.IsInRole("admin"))
                    {

                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="CreateProduct" class="nav-link ">Add Product</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="ProductList" class="nav-link ">Admin Products</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="CreateCategory" class="nav-link ">Add Category</a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Admin" asp-action="CategoryList" class="nav-link ">Admin Categories</a>
                        </li>

                    }
                }

                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Manage" class="nav-link ">@User.Identity.Name</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Logout" class="nav-link ">LogOut</a>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Login" class="nav-link ">Login</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Register" class="nav-link ">Register</a>
                    </li>
                }


            </ul>

        </div>
    </div>
</nav>

ShopApp.WebUI/Views/Shared/_product.cshtml
@model Product
<br />
<br />
<div class="col-md-4">
    <div class="card">
        <img src="~/img/@Model.ImageUrl" alt="@Model.Name" />
        <div class="card-body">
            <h4 class="card-title">
                <a href="#">@Model.Name</a>
            </h4>
            <small class="text-muted">
                <i class="fas fa-lira-sign"></i>@Model.Price
            </small>
        </div>
        <div class="card-footer text-center">
            <a asp-controller="Shop" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-outline-primary btn-sm">Details</a>
            @if (User.Identity.IsAuthenticated)
            {
                <form asp-controller="Cart" asp-action="AddToCart" method="post" style="display:inline;">
                    <input type="hidden"  name="productId" value="@Model.Id"/>
                    <input type="hidden"  name="quantity" value="1"/>
                    <button type="submit" class="btn btn-outline-primary">Add To Cart</button>
                </form>
            }


        </div>
    </div>

    <br />
    <br />
</div>

ShopApp.WebUI/Views/Shared/_resultmessage.cshtml
@model ResultMessage
    <div class="row">


        <div class="col-md-12">
            <div class="alert alert-@Model.Css">

                <h4 class="alert-title">
                    @Model.Title
                </h4><p>
                    @Model.Message
                </p>
            </div>
        </div>
    </div>

ShopApp.WebUI/Views/Shared/_slider.cshtml
<div id="mySlider" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#mySlider" data-slide-to="0" class="active"></li>
        <li data-target="#mySlider" data-slide-to="1"></li>
        <li data-target="#mySlider" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/img/1.jpg" class="d-block img-fluid " />
        </div>

        <div class="carousel-item ">
            <img src="~/img/2.jpg" class="d-block img-fluid " />
        </div>
        <div class="carousel-item ">
            <img src="~/img/3.jpg" class="d-block img-fluid " />
        </div>
    </div>
    <a href="#mySlider" data-slide="prev" role="button" class="carousel-control-prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a href="#mySlider" data-slide="next" role="button" class="carousel-control-next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>